apiVersion: apps/v1 
kind: Pod 
metadata: 
  name: nginx-pod 
spec:
  containers:
  - name: nginx-pod
    image: nginx-latest 
    ports: 
    - containerPort: 80 
    resources: 
      requests: 
        memory: "300Mi"