apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: simple-web 
  labels: 
    app: simple-web
spec: 
  replicas: 2
  selector: 
    matchLabels:
      app: simple-web 
  template: 
    metadata:
      lables:
        app: simple-web
    spec:
      containers:
      - name: simple-web
        image: blueninjas/simple-web:latest
        ports:
        - containerPort: 80
        resources:
          requests: 
            memory: "300Mi"
            cpu: "25m"
          limits: 
            memory: "64Mi"
            cpu: "50m"

--- 

apiVersion: v1
kind: Service 
metadata: 
  name: simple-web-service
  labels: 
    app: simple-web 
spec: 
  type: LoadBalancer 
  ports: 
  - port: 80 
    targetPort: 80 
    protocol: TCP 
  selector: 
    app: simple-web 

---

apiVersion: v1
kind: Service 
metadata: 
  name: simple-web-nodeport
  labels:
    app: simple-web
spec:
  type: NodePort
  ports: 
  - port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP
  selector:
    app: simple-web 
